<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Asset Inventory Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 12px;
            color: #333333;
            margin: 0;
            padding: 0;
        }
        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header table {
            width: 100%;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            color: #1e3a8a;
            margin: 0;
        }
        .subtitle {
            font-size: 12px;
            color: #64748b;
            margin-top: 4px;
        }
        .meta-info {
            text-align: right;
            font-size: 11px;
            color: #475569;
        }
        .summary-cards {
            width: 100%;
            margin-bottom: 20px;
        }
        .summary-card {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 10px;
            text-align: center;
        }
        .summary-card .number {
            font-size: 18px;
            font-weight: bold;
            color: #1e293b;
        }
        .summary-card .label {
            font-size: 10px;
            color: #64748b;
            text-transform: uppercase;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table.data-table th {
            background-color: #1e293b;
            color: #ffffff;
            font-weight: 600;
            font-size: 11px;
            text-align: left;
            padding: 8px 10px;
            text-transform: uppercase;
        }
        table.data-table td {
            padding: 8px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 11px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-active { background-color: #dcfce7; color: #166534; }
        .badge-checked_out { background-color: #dbeafe; color: #1e40af; }
        .badge-maintenance { background-color: #fef3c7; color: #92400e; }
        .badge-archived { background-color: #f3f4f6; color: #374151; }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 30px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            line-height: 30px;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td>
                    <h1 class="title">ScanTrack Assets</h1>
                    <div class="subtitle">Complete Asset Inventory List</div>
                </td>
                <td class="meta-info">
                    <strong>Generated Date:</strong> {{ now()->format('M d, Y H:i') }}<br>
                    <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System Admin' }}
                </td>
            </tr>
        </table>
    </div>

    <table class="summary-cards">
        <tr>
            <td width="32%">
                <div class="summary-card">
                    <div class="number">{{ $assets->count() }}</div>
                    <div class="label">Total Assets</div>
                </div>
            </td>
            <td width="2%"></td>
            <td width="32%">
                <div class="summary-card">
                    <div class="number">{{ number_format($assets->sum('purchase_price'), 0, ',', ' ') }} FCFA</div>
                    <div class="label">Total Portfolio Value</div>
                </div>
            </td>
            <td width="2%"></td>
            <td width="32%">
                <div class="summary-card">
                    <div class="number">{{ $assets->where('status', 'checked_out')->count() }}</div>
                    <div class="label">Currently Checked Out</div>
                </div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Asset Tag</th>
                <th>Asset Name</th>
                <th>Category</th>
                <th>Brand / Model</th>
                <th>Location</th>
                <th>Status</th>
                <th>Value (FCFA)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($assets as $asset)
                <tr>
                    <td><strong>{{ $asset->asset_tag }}</strong></td>
                    <td>{{ $asset->name }}</td>
                    <td>{{ $asset->category->name ?? 'Unassigned' }}</td>
                    <td>{{ $asset->brand ? $asset->brand . ' ' . $asset->model : '-' }}</td>
                    <td>{{ $asset->location ?? 'N/A' }}</td>
                    <td>
                        <span class="badge badge-{{ $asset->status }}">
                            {{ str_replace('_', ' ', $asset->status) }}
                        </span>
                    </td>
                    <td>{{ number_format($asset->purchase_price ?? 0, 0, ',', ' ') }} FCFA</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; padding: 20px;">No assets found in the inventory.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        ScanTrack Asset Management System &bull; Asset Report &bull; Confidentially Generated
    </div>
</body>
</html>
