<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Asset Status & Custody Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 12px;
            color: #333333;
            margin: 0;
            padding: 0;
        }
        .header {
            border-bottom: 2px solid #0284c7;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header table {
            width: 100%;
        }
        .title {
            font-size: 22px;
            font-weight: bold;
            color: #0369a1;
            margin: 0;
        }
        .subtitle {
            font-size: 12px;
            color: #64748b;
            margin-top: 4px;
        }
        .meta-info {
            text-align: right;
            font-size: 11px;
            color: #475569;
        }
        .section-header {
            font-size: 15px;
            font-weight: bold;
            padding: 8px 12px;
            border-radius: 4px;
            margin-top: 25px;
            margin-bottom: 10px;
        }
        .section-out {
            background-color: #e0f2fe;
            color: #0369a1;
            border-left: 4px solid #0284c7;
        }
        .section-in {
            background-color: #dcfce7;
            color: #15803d;
            border-left: 4px solid #16a34a;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        table.data-table th {
            background-color: #334155;
            color: #ffffff;
            font-weight: 600;
            font-size: 10px;
            text-align: left;
            padding: 7px 10px;
            text-transform: uppercase;
        }
        table.data-table td {
            padding: 7px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 11px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-out { background-color: #bae6fd; color: #0369a1; }
        .badge-in { background-color: #bbf7d0; color: #15803d; }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 30px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            line-height: 30px;
        }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td>
                    <h1 class="title">ScanTrack Asset Status Report</h1>
                    <div class="subtitle">Detailed Breakdown of Checked-Out (OUT) vs Available (IN) Assets</div>
                </td>
                <td class="meta-info">
                    <strong>Report Date:</strong> {{ now()->format('M d, Y H:i') }}<br>
                    <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System Admin' }}
                </td>
            </tr>
        </table>
    </div>

    <!-- CHECKED OUT ASSETS (OUT) -->
    <div class="section-header section-out">
        Checked-Out Assets (OUT) &bull; Total: {{ $checkedOutAssets->count() }}
    </div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Asset Tag</th>
                <th>Asset Name</th>
                <th>Category</th>
                <th>Checked Out To / Location</th>
                <th>Checkout Date</th>
                <th>Expected Return</th>
            </tr>
        </thead>
        <tbody>
            @forelse($checkedOutAssets as $asset)
                @php $activeCheckout = $asset->activeCheckout; @endphp
                <tr>
                    <td><strong>{{ $asset->asset_tag }}</strong></td>
                    <td>{{ $asset->name }}</td>
                    <td>{{ $asset->category->name ?? '-' }}</td>
                    <td>
                        {{ $activeCheckout->assigned_to ?? $asset->location ?? 'Assigned External' }}
                    </td>
                    <td>{{ $activeCheckout ? \Carbon\Carbon::parse($activeCheckout->checked_out_at)->format('M d, Y') : '-' }}</td>
                    <td>{{ $activeCheckout && $activeCheckout->expected_return_at ? \Carbon\Carbon::parse($activeCheckout->expected_return_at)->format('M d, Y') : 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; color: #64748b; padding: 15px;">
                        No assets are currently checked out.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- IN-STOCK / AVAILABLE ASSETS (IN) -->
    <div class="section-header section-in">
        Available In-Stock Assets (IN) &bull; Total: {{ $availableAssets->count() }}
    </div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Asset Tag</th>
                <th>Asset Name</th>
                <th>Category</th>
                <th>Brand / Model</th>
                <th>Current Location</th>
                <th>Condition</th>
            </tr>
        </thead>
        <tbody>
            @forelse($availableAssets as $asset)
                <tr>
                    <td><strong>{{ $asset->asset_tag }}</strong></td>
                    <td>{{ $asset->name }}</td>
                    <td>{{ $asset->category->name ?? '-' }}</td>
                    <td>{{ $asset->brand ? $asset->brand . ' ' . $asset->model : '-' }}</td>
                    <td>{{ $asset->location ?? 'Main Storage' }}</td>
                    <td>{{ $asset->condition ?? 'Good' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; color: #64748b; padding: 15px;">
                        No assets in stock currently.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        ScanTrack Asset Management System &bull; Custody Status Audit &bull; Confidential
    </div>
</body>
</html>
